Enum heuristics_type {
    # --- DOMÍNIO ---
    DOMAIN_AGE
    DOMAIN_EXPIRATION
    DOMAIN_TLD_RISK
    DOMAIN_IS_IP_ADDRESS
    DOMAIN_SIMILAR_TO_BRAND
    DOMAIN_SENSITIVE_KEYWORDS
    DOMAIN_MULTIPLE_SUBLEVELS
    DOMAIN_HYPHENS_USAGE
    DOMAIN_HAS_HTTPS
    DOMAIN_SSL_INVALID
    DOMAIN_DNS_ANOMALY
    DOMAIN_REVERSE_LOOKUP_FAIL
    DOMAIN_GEOLOCATION_RISK

    # --- CAMINHO ---
    PATH_LENGTH_EXCESSIVE
    PATH_COMPLEXITY_HIGH
    PATH_ADMIN_DIRECTORIES
    PATH_FAKE_FILENAME
    PATH_DOUBLE_EXTENSION
    PATH_EXECUTABLE_DISGUISED
    PATH_SOCIAL_ENGINEERING_TERMS

    # --- PARÂMETROS ---
    PARAMS_EXCESSIVE_NUMBER
    PARAMS_SENSITIVE_VARIABLES
    PARAMS_LONG_OR_ENCODED_VALUES
    PARAMS_REDIRECT_KEYWORD
    PARAMS_PERSONAL_DATA_INCLUDED

    # --- ENCURTADORES E REDIRECIONADORES ---
    SHORTENER_USAGE
    MULTIPLE_REDIRECTS
    EMBEDDED_PROTOCOLS

    # --- PADRÕES DE ENGENHARIA SOCIAL ---
    LANGUAGE_MIX
    EMOJI_OR_SYMBOL_USAGE
    ATTRACTIVE_PHRASES
    KEYWORD_REPETITION
    BRAND_IMPERSONATION
}

Enum heuristics_severity {
    LOW
    MEDIUM
    HIGH
    CRITICAL
}

Enum heuristics_status {
    TRUE
    FALSE
}

Enum reputation_source {
    VIRUSTOTAL
    PHISHTANK
    GOOGLE_SAFE_BROWSING
}

Enum reputation_status {
    POSITIVE
    NEGATIVE
}
